import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.MIMOCODE_MODELS_URL || "https://models.dev"
const cachePath = path.join(dir, "node_modules", ".cache", "mimo-models-api.json")
const useCache = process.env.MIMO_MODELS_CACHE === "1"

const getCached = async () => {
  try {
    const stat = await fs.promises.stat(cachePath)
    const ageHours = (Date.now() - stat.mtimeMs) / (1000 * 60 * 60)
    if (ageHours < 24) {
      return await Bun.file(cachePath).text()
    }
  } catch {}
  return null
}

const writeCache = async (data: string) => {
  try {
    await fs.promises.mkdir(path.dirname(cachePath), { recursive: true })
    await Bun.write(cachePath, data)
  } catch {}
}

let modelsData: string | null = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : null

if (modelsData === null && useCache) {
  const cached = await getCached()
  if (cached !== null) {
    console.log("[Cache] Using cached models.dev snapshot")
    modelsData = cached
  }
}

if (modelsData === null) {
  console.log(`[Fetch] Downloading ${modelsUrl}/api.json`)
  const freshData = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  if (useCache) await writeCache(freshData)
  modelsData = freshData
}

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
